# Import The numpy

In [73]:
import numpy as np

# Array Creation

In [28]:
x = np.array([3,21,93])
x

array([ 3, 21, 93])

In [3]:
x = np.array(3,21,93)

ValueError: only 2 non-keyword arguments accepted

In [31]:
x = np.array([[12,32,29], [92,43,39]])

In [18]:
x

array([[12, 32, 29],
       [92, 43, 39]])

In [19]:
x = np.array([(1.5,2,3), (4,5,6)])
x

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
c = np.array( [ [12,24], [36,48] ], dtype=float )

In [21]:
c

array([[1., 2.],
       [3., 4.]])

# Array Attributes

In [29]:
x.ndim

1

In [35]:
x.shape

(2, 3)

In [39]:
x.dtype

dtype('int64')

In [40]:
x.itemsize

8

In [41]:
x.data

# Null arrays

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# Unit Arrays

In [44]:
np.ones( (2,4,5), dtype=np.int32 ) 

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [46]:
np.empty( (2,2) )   

array([[1., 2.],
       [3., 4.]])

In [47]:
np.arange( 5, 50, 3 )

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [50]:
np.arange( 100, 5, -10 )

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [51]:
np.arange( 1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Printing Arrays

In [61]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
y = np.arange(10).reshape(2,5)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [65]:
z = np.arange(30).reshape(2,5,3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


# Basic Operations

In [69]:
x = np.random.random((2,3))
x

array([[0.14253852, 0.41326794, 0.83596231],
       [0.9898787 , 0.24807254, 0.19113084]])

In [70]:
x.sum()

2.8208508606801543

In [71]:
x.min()

0.14253852257804456

In [72]:
x.max()

0.9898787026890289

In [73]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
y.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [76]:
y.max(axis=1) 

array([4, 9])

In [78]:
y.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [79]:
y.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]])

In [4]:
x = np.array( [0,1,2,3] )
y = np.arange( 4 )
y


array([0, 1, 2, 3])

# Arithmatic operations

In [6]:
z = x-y
print(z)

[0 0 0 0]


In [7]:
y**2

array([0, 1, 4, 9])

In [8]:
100*np.sin(x)

array([ 0.        , 84.14709848, 90.92974268, 14.11200081])

In [11]:
w = 2
print(x<w)


[ True  True False False]


In [13]:
x = np.array( [[1,2],
              [3,4]] )
y = np.array( [[1,2],
              [3,4]] )

In [14]:
x*y

array([[ 1,  4],
       [ 9, 16]])

In [15]:
x@y

array([[ 7, 10],
       [15, 22]])

In [16]:
x.dot(y)

array([[ 7, 10],
       [15, 22]])

In [20]:
x = np.array( [[1],
              [3]] )
y = np.array( [[1,2],
              [3,4]] )

In [22]:
y@x

array([[ 7],
       [15]])

In [27]:
x = np.ones((2,2), dtype=int)
y = np.random.random((2,2))
x *= 5
print(x)



[[5 5]
 [5 5]]


In [28]:
print(y)

[[0.1992092  0.04866274]
 [0.34701818 0.52960714]]


In [29]:
y += x
y


array([[5.1992092 , 5.04866274],
       [5.34701818, 5.52960714]])

In [26]:
x += y
Print (x) 

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

# universtal Function

In [30]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [31]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [32]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [33]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [34]:
y = np.array([-1,2,-5,2,10])
np.add(x,y)

array([-1,  3, -3,  5, 14])

# Indexing, Slicing and Iteration

In [36]:
x = np.arange(10, 30, 2)
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [37]:
print(x[0])

10


In [38]:
print(x[-1])

28


In [40]:
print(x[3])

16


In [44]:
print(x[8])

26


In [42]:
print(x[-2])

26


In [45]:
x = np.arange(10, 30, 2).reshape(2,5)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [46]:
print(x[0,1])

12


In [47]:
print(x[1,4])

28


In [48]:
print(x[1,-2])

26


In [49]:
x = np.arange(10, 40, 2).reshape(3,5)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [50]:
x[2]

array([30, 32, 34, 36, 38])

In [52]:
x[:,1]

array([12, 22, 32])

In [53]:
x[1,:]

array([20, 22, 24, 26, 28])

In [54]:
x = np.arange(10, 30, 2)
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [55]:
print(x[0:2])

[10 12]


In [57]:
x[6:-1]

array([22, 24, 26])

In [58]:
x[-1:4]

array([], dtype=int64)

In [60]:
y = x[3:9]
y

array([16, 18, 20, 22, 24, 26])

In [61]:
y[2] = 100

In [62]:
y

array([ 16,  18, 100,  22,  24,  26])

In [64]:
x = np.arange(10, 40, 2).reshape(3,5)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [72]:
x[1,0:2]

array([20, 22])

In [66]:
x[:,2:4]

array([[14, 16],
       [24, 26],
       [34, 36]])

In [67]:
x[1:,1:5]

array([[22, 24, 26, 28],
       [32, 34, 36, 38]])

In [69]:
x[:,:3]

array([[10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

In [71]:
x[-2:, 0:-2]

array([[20, 22, 24],
       [30, 32, 34]])

In [75]:
x = np.arange(10, 70, 2).reshape(2,3,5)
x

array([[[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38]],

       [[40, 42, 44, 46, 48],
        [50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68]]])

In [76]:
x[0, 0:2, 1:4]

array([[12, 14, 16],
       [22, 24, 26]])

In [77]:
x = np.arange(10, 40, 2).reshape(3,5)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [78]:
for row in x:
    print(row)

[10 12 14 16 18]
[20 22 24 26 28]
[30 32 34 36 38]


In [80]:
y = x.T
y

array([[10, 20, 30],
       [12, 22, 32],
       [14, 24, 34],
       [16, 26, 36],
       [18, 28, 38]])

In [83]:
for row in (y):
    print(row)

[10 20 30]
[12 22 32]
[14 24 34]
[16 26 36]
[18 28 38]


In [84]:
for row in (y>24):
    print(row)

[False False  True]
[False False  True]
[False False  True]
[False  True  True]
[False  True  True]


In [87]:
for row in y.flat:
    print(row)

10
20
30
12
22
32
14
24
34
16
26
36
18
28
38


In [88]:
for a in np.nditer(x):
    print(a)


10
12
14
16
18
20
22
24
26
28
30
32
34
36
38


In [91]:
for a in np.nditer(x, order = 'C'):
    print(a)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38


In [94]:
for a in np.nditer(x, order = 'c'):
    print(a)

ValueError: order must be one of 'C', 'F', 'A', or 'K'

# Shape Manipulation

In [114]:
x = np.arange(10, 40, 2)
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [116]:
x.reshape(3,5)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [99]:
np.reshape(x, (15,1))

array([[10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38]])

In [100]:
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [102]:
y = x.reshape(3,5)
y

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [104]:
y.ravel()

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [113]:
x.resize(3,5)
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [108]:
x

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

# Stacking

In [121]:
x = np.array([[1,2],[3,4]]) 
print(x)

[[1 2]
 [3 4]]


In [120]:
y = np.array([[5,6],[7,8]])
print(y)

[[5 6]
 [7 8]]


In [124]:
print(np.stack((x,y),0) )

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [125]:
print(np.stack((x,y),1) )

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [129]:
print(np.vstack((x,y)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [130]:
print(np.hstack((x,y)))

[[1 2 5 6]
 [3 4 7 8]]


In [131]:
x = np.array([0, 10, 20, 30, 40, 50, 60, 70])

y = np.array_split(x, 4)

print(y)

[array([ 0, 10]), array([20, 30]), array([40, 50]), array([60, 70])]


# splitting

In [136]:
x = np.floor(10*np.random.random((2,12)))
x

array([[1., 5., 9., 7., 6., 3., 7., 9., 1., 4., 6., 7.],
       [4., 6., 6., 2., 9., 8., 8., 0., 5., 6., 8., 1.]])

In [137]:
print(np.hsplit(x, 3))

[array([[1., 5., 9., 7.],
       [4., 6., 6., 2.]]), array([[6., 3., 7., 9.],
       [9., 8., 8., 0.]]), array([[1., 4., 6., 7.],
       [5., 6., 8., 1.]])]


In [140]:
print(np.hsplit(x, (3,4,7)))

[array([[1., 5., 9.],
       [4., 6., 6.]]), array([[7.],
       [2.]]), array([[6., 3., 7.],
       [9., 8., 8.]]), array([[9., 1., 4., 6., 7.],
       [0., 5., 6., 8., 1.]])]


In [141]:
id(x)

140465565538464